export const ProductService = {
    getProductsData() {
        return [
            
            {
                id: '651535',                
                TaskName: 'DO Collection',
                TaskStatus: 'Incomplete',
                sla: '-10 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'C&F Agent',
                EscalationRaised: 'Yes',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE1',
                TaskSLA: 'Delayed',
                action: 'test',
                invoicenumber:'EF-QARTG',
                approvreject:'Subastian Shaw',
                designation:'Finance Head',
                invodocname:'Shipment Cost',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            },
            {
                id: '267400',
                TaskName: 'Shipment Clearance',
                TaskStatus: 'Complete',
                sla: '4 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'COE 1',
                EscalationRaised: 'No',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE2',
                TaskSLA: 'Urgent',
                action: 'test',                
                invodocname:'Transport Cost',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            },
            {
                id: '267350',
                TaskName: 'BOE Filing',
                TaskStatus: 'Complete',
                sla: '16 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'C&F Agent',
                EscalationRaised: 'Yes',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE1',
                TaskSLA: 'On Time',
                action: 'test',
                invodocname:'Invoice',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            }, 
            {
                id: '651535',
                TaskName: 'DO Collection',
                TaskStatus: 'Incomplete',
                sla: '-10 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'C&F Agent',
                EscalationRaised: 'Yes',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE1',
                TaskSLA: 'Delayed',
                action: 'test',
                invodocname:'Shipment Cost',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            },
            {
                id: '267400',
                TaskName: 'Shipment Clearance',
                TaskStatus: 'Complete',
                sla: '4 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'COE 1',
                EscalationRaised: 'No',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE2',
                TaskSLA: 'Urgent',
                action: 'test',
                invodocname:'Shipment Cost',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            },
            {
                id: '651535',
                TaskName: 'DO Collection',
                TaskStatus: 'Incomplete',
                sla: '-10 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'C&F Agent',
                EscalationRaised: 'Yes',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE1',
                TaskSLA: 'Delayed',
                action: 'test',
                invodocname:'Shipment Cost',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            },
            {
                id: '267400',
                TaskName: 'Shipment Clearance',
                TaskStatus: 'Complete',
                sla: '4 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'COE 1',
                EscalationRaised: 'No',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE2',
                TaskSLA: 'Urgent',
                action: 'test',
                invodocname:'Shipment Cost',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            },
            {
                id: '267350',
                TaskName: 'BOE Filing',
                TaskStatus: 'Complete',
                sla: '16 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'C&F Agent',
                EscalationRaised: 'Yes',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE1',
                TaskSLA: 'On Time',
                action: 'test',
                invodocname:'Shipment Cost',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            }, 
            {
                id: '651535',
                TaskName: 'DO Collection',
                TaskStatus: 'Incomplete',
                sla: '-10 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'C&F Agent',
                EscalationRaised: 'Yes',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE1',
                TaskSLA: 'Delayed',
                action: 'test',
                invodocname:'Shipment Cost',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            },
            {
                id: '267400',
                TaskName: 'Shipment Clearance',
                TaskStatus: 'Complete',
                sla: '4 Hours',
                reported: '3/1/2023 11:00 AM IST',
                pending: 'COE 1',
                EscalationRaised: 'No',
                EscalationRaisedOn: '3/1/2023 10:00 AM',
                EscalationRaisedBy: 'COE2',
                TaskSLA: 'Urgent',
                action: 'test',
                invodocname:'Shipment Cost',
                invoupload:'08/01/2023',
                invoremarks:'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
            },
                      
           
        ];
    },


    getProductsMini() {
        return Promise.resolve(this.getProductsData().slice(0, 3));
    },

    getProductsSmall() {
        return Promise.resolve(this.getProductsData().slice(0, 10));
    },

    getProducts() {
        return Promise.resolve(this.getProductsData());
    },

    getProductsWithOrdersSmall() {
        return Promise.resolve(this.getProductsWithOrdersData().slice(0, 10));
    },

    getProductsWithOrders() {
        return Promise.resolve(this.getProductsWithOrdersData());
    }
};

